# Generated by Django 4.2.7 on 2023-11-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_axisbankstockdata_rsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axisbankstockdata',
            name='RSI',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
