# Generated by Django 4.2.7 on 2023-11-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_axisbankstockdata_rsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axisbankstockdata',
            name='Close_Price',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='axisbankstockdata',
            name='High_Price',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='axisbankstockdata',
            name='Low_Price',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='axisbankstockdata',
            name='Lower_Band',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='axisbankstockdata',
            name='MA',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='axisbankstockdata',
            name='MACD',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='axisbankstockdata',
            name='Middle_Band',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='axisbankstockdata',
            name='Open_Price',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='axisbankstockdata',
            name='Percent_D',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='axisbankstockdata',
            name='Percent_K',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='axisbankstockdata',
            name='Prev_Close_Price',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='axisbankstockdata',
            name='Signal_Line',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='axisbankstockdata',
            name='Total_Traded_Value',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='axisbankstockdata',
            name='Upper_Band',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='axisbankstockdata',
            name='VWAP',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='axisbankstockdata',
            name='Week_High_Price_52',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='axisbankstockdata',
            name='Week_Low_Price_52',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
