# Generated by Django 4.2.7 on 2023-11-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_alter_hindalcostockdata_bollinger_recommendation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company_name', models.CharField(max_length=100)),
                ('open_price', models.CharField(max_length=100)),
                ('high_price', models.CharField(max_length=100)),
                ('low_price', models.CharField(max_length=100)),
                ('close_price', models.CharField(max_length=100)),
                ('prev_close_price', models.CharField(max_length=100)),
                ('total_traded_quantity', models.CharField(max_length=100)),
                ('total_traded_value', models.CharField(max_length=100)),
                ('week_high_price_52', models.CharField(max_length=100)),
                ('week_low_price_52', models.CharField(max_length=100)),
                ('vwap', models.CharField(max_length=100)),
                ('deliverable_volume', models.CharField(blank=True, max_length=100, null=True)),
                ('deliverable_percent', models.CharField(blank=True, max_length=100, null=True)),
                ('series', models.CharField(max_length=100)),
                ('rsi', models.CharField(blank=True, max_length=100, null=True)),
                ('upper_band', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_band', models.CharField(blank=True, max_length=100, null=True)),
                ('lower_band', models.CharField(blank=True, max_length=100, null=True)),
                ('percent_k', models.CharField(blank=True, max_length=100, null=True)),
                ('percent_d', models.CharField(blank=True, max_length=100, null=True)),
                ('macd', models.CharField(blank=True, max_length=100, null=True)),
                ('signal_line', models.CharField(blank=True, max_length=100, null=True)),
                ('ma', models.CharField(blank=True, max_length=100, null=True)),
                ('rsi_recommendation', models.CharField(max_length=100)),
                ('bollinger_recommendation', models.CharField(max_length=100)),
                ('stochastic_recommendation', models.CharField(max_length=100)),
                ('macd_recommendation', models.CharField(max_length=100)),
                ('ma_recommendation', models.CharField(max_length=100)),
            ],
        ),
    ]
