# Generated by Django 4.2.7 on 2023-11-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_aggregatedstockdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aggregatedstockdata',
            old_name='deliverable_percent',
            new_name='Bollinger_Recommendation',
        ),
        migrations.RenameField(
            model_name='aggregatedstockdata',
            old_name='deliverable_volume',
            new_name='Close_Price',
        ),
        migrations.RenameField(
            model_name='aggregatedstockdata',
            old_name='lower_band',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='aggregatedstockdata',
            old_name='ma',
            new_name='Deliverable_Percent',
        ),
        migrations.RenameField(
            model_name='aggregatedstockdata',
            old_name='macd',
            new_name='Deliverable_Volume',
        ),
        migrations.RenameField(
            model_name='aggregatedstockdata',
            old_name='middle_band',
            new_name='High_Price',
        ),
        migrations.RenameField(
            model_name='aggregatedstockdata',
            old_name='percent_d',
            new_name='Low_Price',
        ),
        migrations.RenameField(
            model_name='aggregatedstockdata',
            old_name='percent_k',
            new_name='Lower_Band',
        ),
        migrations.RenameField(
            model_name='aggregatedstockdata',
            old_name='rsi',
            new_name='MA',
        ),
        migrations.RenameField(
            model_name='aggregatedstockdata',
            old_name='signal_line',
            new_name='MACD',
        ),
        migrations.RenameField(
            model_name='aggregatedstockdata',
            old_name='upper_band',
            new_name='MACD_Recommendation',
        ),
        migrations.RemoveField(
            model_name='aggregatedstockdata',
            name='bollinger_recommendation',
        ),
        migrations.RemoveField(
            model_name='aggregatedstockdata',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='aggregatedstockdata',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='aggregatedstockdata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='aggregatedstockdata',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='aggregatedstockdata',
            name='low_price',
        ),
        migrations.RemoveField(
            model_name='aggregatedstockdata',
            name='ma_recommendation',
        ),
        migrations.RemoveField(
            model_name='aggregatedstockdata',
            name='macd_recommendation',
        ),
        migrations.RemoveField(
            model_name='aggregatedstockdata',
            name='open_price',
        ),
        migrations.RemoveField(
            model_name='aggregatedstockdata',
            name='prev_close_price',
        ),
        migrations.RemoveField(
            model_name='aggregatedstockdata',
            name='rsi_recommendation',
        ),
        migrations.RemoveField(
            model_name='aggregatedstockdata',
            name='series',
        ),
        migrations.RemoveField(
            model_name='aggregatedstockdata',
            name='stochastic_recommendation',
        ),
        migrations.RemoveField(
            model_name='aggregatedstockdata',
            name='total_traded_quantity',
        ),
        migrations.RemoveField(
            model_name='aggregatedstockdata',
            name='total_traded_value',
        ),
        migrations.RemoveField(
            model_name='aggregatedstockdata',
            name='vwap',
        ),
        migrations.RemoveField(
            model_name='aggregatedstockdata',
            name='week_high_price_52',
        ),
        migrations.RemoveField(
            model_name='aggregatedstockdata',
            name='week_low_price_52',
        ),
        migrations.AddField(
            model_name='aggregatedstockdata',
            name='Middle_Band',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aggregatedstockdata',
            name='Percent_D',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aggregatedstockdata',
            name='Percent_K',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aggregatedstockdata',
            name='RSI',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aggregatedstockdata',
            name='Signal_Line',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aggregatedstockdata',
            name='Upper_Band',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aggregatedstockdata',
            name='MA_Recommendation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aggregatedstockdata',
            name='Open_Price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aggregatedstockdata',
            name='Prev_Close_Price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aggregatedstockdata',
            name='RSI_Recommendation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aggregatedstockdata',
            name='Series',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aggregatedstockdata',
            name='Stochastic_Recommendation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aggregatedstockdata',
            name='Total_Traded_Quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aggregatedstockdata',
            name='Total_Traded_Value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aggregatedstockdata',
            name='VWAP',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aggregatedstockdata',
            name='Week_High_Price_52',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aggregatedstockdata',
            name='Week_Low_Price_52',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
